# soc2_controls.py
# SOC 2 (Security) control-inspired question bank for an MVP readiness checker.
# Plain-English summaries only (no proprietary text).

SOC2_CONTROLS = [
    {
        "id": "mfa_admin",
        "category": "Access Control (CC6)",
        "question": "Do you enforce MFA for all admin accounts and remote access (VPN/email/cloud consoles)?",
        "cc": ["CC6.1"],
        "weight": 3,
        "owner": "IT / Security",
        "fix": "Require MFA for all privileged accounts and for remote access. Disable legacy auth where possible.",
        "evidence": ["MFA/Conditional Access policy", "IdP screenshots (Entra/Google)", "Admin account list", "Authentication logs"],
    },
    {
        "id": "least_privilege",
        "category": "Access Control (CC6)",
        "question": "Do you enforce least privilege (role-based access) and avoid shared admin accounts?",
        "cc": ["CC6.2", "CC6.3"],
        "weight": 3,
        "owner": "IT / Security",
        "fix": "Eliminate shared admin accounts, use named accounts, implement RBAC, and restrict privileged roles.",
        "evidence": ["Privileged role assignment export", "Admin account inventory", "JML (joiner/mover/leaver) procedure", "Access request/approval tickets"],
    },
    {
        "id": "access_reviews",
        "category": "Access Control (CC6)",
        "question": "Do you perform user access reviews at least quarterly for key systems?",
        "cc": ["CC6.3"],
        "weight": 2,
        "owner": "IT / Security",
        "fix": "Implement quarterly access reviews with documented approvals and removal actions for key apps and admin roles.",
        "evidence": ["Access review spreadsheet", "Approval emails/tickets", "Role change logs", "Termination/offboarding checklist"],
    },
    {
        "id": "password_policy",
        "category": "Access Control (CC6)",
        "question": "Do you have a strong password policy (length, banned passwords) and protect against credential reuse?",
        "cc": ["CC6.1"],
        "weight": 2,
        "owner": "IT / Security",
        "fix": "Enforce strong password requirements and banned password lists; require SSO where possible; monitor for leaked creds.",
        "evidence": ["Password policy settings screenshot", "SSO configuration", "Banned password settings", "Credential monitoring procedure"],
    },
    {
        "id": "offboarding",
        "category": "Access Control (CC6)",
        "question": "Do you disable accounts and remove access promptly when an employee/contractor leaves?",
        "cc": ["CC6.2"],
        "weight": 3,
        "owner": "IT / HR",
        "fix": "Create a formal offboarding process that removes access within a defined SLA and documents completion.",
        "evidence": ["Offboarding checklist", "HR termination ticket", "Account disable logs", "Access removal confirmations"],
    },
    {
        "id": "device_security",
        "category": "System Operations (CC7)",
        "question": "Are company devices managed and secured (encryption, screen lock, EDR/AV, patching baseline)?",
        "cc": ["CC7.1"],
        "weight": 2,
        "owner": "IT",
        "fix": "Enforce device encryption, MDM policies, EDR/AV, and baseline configurations for endpoints.",
        "evidence": ["MDM/Intune policy screenshots", "Device encryption status", "EDR/AV dashboard", "Baseline config documentation"],
    },
    {
        "id": "central_logging",
        "category": "Monitoring & Detection (CC7)",
        "question": "Do you centrally collect logs (IdP, endpoints, cloud) and retain them for investigation?",
        "cc": ["CC7.2"],
        "weight": 3,
        "owner": "Security",
        "fix": "Centralize log collection and define log retention; ensure key sources (IdP, endpoints, cloud) are included.",
        "evidence": ["SIEM/log platform screenshots", "Log source list", "Retention settings", "Sample investigation query"],
    },
    {
        "id": "alerting",
        "category": "Monitoring & Detection (CC7)",
        "question": "Do you have alerting/monitoring for suspicious activity (admin changes, impossible travel, malware alerts)?",
        "cc": ["CC7.3"],
        "weight": 2,
        "owner": "Security",
        "fix": "Define alert rules for key detections and ensure alerts are reviewed and tracked to closure.",
        "evidence": ["Alert rule list", "Sample alerts", "Ticket/incident workflow", "On-call/notification settings"],
    },
    {
        "id": "incident_response_plan",
        "category": "Incident Response (CC7)",
        "question": "Do you have an incident response plan with roles, escalation steps, and a severity model?",
        "cc": ["CC7.4"],
        "weight": 3,
        "owner": "Security",
        "fix": "Create an Incident Response Plan (roles, severity, escalation, comms) and keep it reviewed/approved.",
        "evidence": ["Incident Response Plan", "Escalation matrix", "Contact list", "IR approval record"],
    },
    {
        "id": "ir_testing",
        "category": "Incident Response (CC7)",
        "question": "Do you run incident response tabletop exercises (at least annually) and track lessons learned?",
        "cc": ["CC7.4"],
        "weight": 2,
        "owner": "Security",
        "fix": "Run tabletop exercises and document outcomes; convert gaps into remediation tasks with owners and dates.",
        "evidence": ["Tabletop agenda", "Meeting notes", "Action items list", "Follow-up tickets"],
    },
    {
        "id": "vulnerability_mgmt",
        "category": "Vulnerability & Patching (CC7)",
        "question": "Do you scan for vulnerabilities and patch critical/high issues on a defined cadence?",
        "cc": ["CC7.1"],
        "weight": 2,
        "owner": "IT / Security",
        "fix": "Establish vulnerability scanning and patch SLAs (critical/high) and track remediation in tickets.",
        "evidence": ["Vuln scan reports", "Patch policy", "Remediation tickets", "Exception approvals"],
    },
    {
        "id": "backups_restore",
        "category": "Resilience (CC7)",
        "question": "Do you have backups and perform restore tests to prove they work?",
        "cc": ["CC7.4"],
        "weight": 2,
        "owner": "IT",
        "fix": "Implement regular backups and scheduled restore testing; document results and failures.",
        "evidence": ["Backup schedule", "Restore test results", "Backup tool configuration", "RPO/RTO targets"],
    },
    {
        "id": "change_mgmt",
        "category": "Change Management (CC8)",
        "question": "Do you track and approve production changes (tickets/PRs), including testing and rollback?",
        "cc": ["CC8.1"],
        "weight": 2,
        "owner": "Engineering / IT",
        "fix": "Use change management with approvals, testing evidence, and rollback plans for production changes.",
        "evidence": ["Change tickets", "PR approval screenshots", "Deployment logs", "Rollback procedure"],
    },
    {
        "id": "vendor_risk",
        "category": "Vendor Management (CC9)",
        "question": "Do you assess vendor security risk before onboarding (questionnaire, SOC 2 report, contract clauses)?",
        "cc": ["CC9.2"],
        "weight": 2,
        "owner": "Security / Procurement",
        "fix": "Implement vendor intake/security review and require security terms, DPAs, and SOC 2 where applicable.",
        "evidence": ["Vendor questionnaire", "Signed security addendum/DPA", "Vendor risk rating", "SOC 2 report (if available)"],
    },
    {
        "id": "security_training",
        "category": "Security Awareness (CC2)",
        "question": "Do you provide security awareness training and track completion (at least annually)?",
        "cc": ["CC2.2"],
        "weight": 1,
        "owner": "HR / Security",
        "fix": "Deliver security awareness training and track completion; include phishing/social engineering content.",
        "evidence": ["Training content", "Completion reports", "New-hire training checklist", "Policy acknowledgements"],
    },
]
